name: "Docker Build & Push Action"
description: "Reusable Docker build and push steps"

inputs:
  image_name:
    description: "Docker image name"
    required: true
  registry_name:
    description: "ACR registry name"
    required: true
  version:
    description: "Image version"
    required: true
  working-directory:
    description: "Working directory for the Dockerfile"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build Docker image
      run: |
        echo "Image name: ${{ inputs.image_name }}"
        docker build -t ${{ inputs.registry_name }}.azurecr.io/${{ inputs.image_name }}:${{ inputs.version }} .
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Push Docker image to ACR
      run: |
        docker push ${{ inputs.registry_name }}.azurecr.io/${{ inputs.image_name }}:${{ inputs.version }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
