name: app

environment: prod

<<<<<<< HEAD
<<<<<<< HEAD
replicas: 1

image:
  repository: venkatsunilmprod.azurecr.io
=======
replicas: 2

image:
  repository: venkatsunilm.azurecr.io
>>>>>>> 63b6df2 (Feat: Separate pipelines for infrastructure and app deployments (#33))
=======
replicas: 1

image:
  repository: venkatsunilmprod.azurecr.io
>>>>>>> 2e4e7e2 (Feat(cicd_new_design): Implement Full CI/CD Pipeline with Dynamic Environment Support and Reusable Actions (#44))
  name: data-upload-app
  tag: "latest"
  pullPolicy: IfNotPresent